# Generated by Django 2.2.7 on 2019-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('short_code', models.CharField(blank=True, max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('counted', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Urls',
            },
        ),
    ]
