# Generated by Django 2.2.7 on 2019-11-12 14:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('short_code', models.CharField(blank=True, max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('counted', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Urls',
            },
            managers=[
                ('urls', django.db.models.manager.Manager()),
            ],
        ),
    ]
